### ISSUE TITLE
does it support SM-N975F(d2s) aka note 10 plus?

### ISSUE THREAD

**Issue by swapnanil1** [ravindu644/Beyondx-KSU#1]
I am aware of this KSU supporting s10 as mentioned in the xda post. but in the releases page there is a N10 version that is why i have to ask is this kernel compatible with N10 AND N10+ series? or just N10 .

And if not is this project has future plans to implement so for all Exynos 9820 devices?

**Comment by ravindu644** [comment]
Yes it should work. I tested it in a Normal Note 10 with my tester. He said, it worked.

I'll build KSU and Magisk images for all the Note 10 and S 10 series after exams.
